use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum EscrowError {
    InvalidAmount = 1,
    Unauthorized = 2,
    EscrowNotFound = 3,
    AlreadyFunded = 4,
    InvalidStatus = 5,
    AlreadyReleased = 6,
    AlreadyRefunded = 7,
    TransferFailed = 8,
    EscrowAlreadyExists = 9,
    InsufficientBalance = 10,
    InvalidStateTransition = 11,
    DeadlineExpired = 12,
    DeadlineNotPassed = 13,
    EscrowAlreadyCancelled = 14,
    CannotModifyFundedEscrow = 15,
    MilestoneNotFound = 16,
    DisputeAlreadyRaised = 17,
    NoActiveDispute = 18,
    FeeTransferFailed = 19,
    InvalidFeePercentage = 20,
    AdminRequired = 21,
    ContractPaused = 22,
    InvalidToken = 23,
    DeadlineInPast = 24,
    UnauthorizedAction = 25,
    MilestoneAmountMismatch = 26,
    MilestoneCountMismatch = 27,
    MilestoneAlreadyReleased = 28,
    CannotReleaseUnapprovedMilestone = 29,
    CannotSubmitAlreadySubmittedMilestone = 30,
    ZeroMilestones = 31,
    EscrowAlreadyReleased = 32,
    EscrowAlreadyRefunded = 33,
    InvalidDeadlineTransition = 34,
    TreasuryNotConfigured = 35,
    CannotSetFeeExceedingMax = 36,
}
